story/TYTA-130/refactor-connected-layout-sidebar
TimeYourTask/Tyta-frontend pull request #27
Opened 2022-12-13 13:56 UTC by remirubis

### Description

I completely recreated the layout management when the user is logged in to manage the size of each part while allowing the user to close or open the menu. The rendering remains the same overall but fixes the problem @FabienHP  had previously pointed out concerning the size of the toolbar in height :)

2022-12-13 20:57 UTC, FabienHP requested changes

2022-12-13 20:57 UTC, FabienHP commented on src/components/Layouts/Connected/Connected.layout.jsx
> +          <OpenIcon />
Suggest style for a more visible icon

<img width="55" alt="image" src="https://user-images.githubusercontent.com/54967480/207441582-681bccf6-0e95-4512-aa52-47c83eea445f.png">

<img width="301" alt="image" src="https://user-images.githubusercontent.com/54967480/207441673-282ccdac-2f7d-408a-b5b6-f26317659935.png">


```suggestion
            border: 'solid rgba(0, 0, 0, 0.12)',
            borderWidth: '1px 1px 1px 0',
            borderRadius: '0 4px 4px 0',
            position: 'absolute',
            padding: '4px',
            top: 3,
            left: 0,
            opacity: 100,
          }}
        >
          <OpenIcon sx={{ transform: open && 'rotate(180deg)' }} />
```

2022-12-13 22:20 UTC, BrystoQ approved these changes, later dismissed
Seems legit to me, but Fabien's change are good

2022-12-15 08:36 UTC, FabienHP approved these changes

2022-12-15 08:36 UTC, merged