feat(Header): Implement an appbar on all page
TimeYourTask/Tyta-frontend pull request #7
Opened 2022-11-21 18:13 UTC by FabienHP

2022-11-21 20:59 UTC, remirubis requested changes
Few changes :)

2022-11-21 20:59 UTC, remirubis commented on src/App.js
>    const { message } = useSelector(state => state.init)
Are you configured Eslint? It seems that there are not the necessary rules.

2022-11-21 21:00 UTC, remirubis commented on src/App.js
>    const { message } = useSelector(state => state.init)
Line 8 -> Missing comma

2022-11-22 13:47 UTC, remirubis submitted a review, later dismissed
LGTM

2022-11-22 13:50 UTC, remirubis approved these changes, later dismissed

2022-11-22 13:51 UTC, remirubis commented
For working on another ticket I made a rebase and I merged it 😄

2022-11-22 14:02 UTC, remirubis approved these changes

2022-11-22 14:25 UTC, kilianpichard approved these changes
LGTM !

2022-11-22 14:25 UTC, merged